# Generated by Django 6.1.1 on 2026-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='analisado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='erro_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='resumo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='status_ia',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, default=''),
        ),
    ]
