# Generated by Django 6.1.1 on 2026-09-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documento_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
