# Generated by Django 6.1.1 on 2026-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo_convertido',
            field=models.FileField(blank=True, null=True, upload_to='documentos/convertidos/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='convertido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='erro_conversao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documento',
            name='status_conversao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
